spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/members
    username: root
    password: tanatos5445
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none